// lib/lic-products.ts

export interface Nature {
  participating: boolean
  linked: boolean
  type: string
}

export interface Eligibility {
  min_age: number | null
  max_age: number | null
  term_range_years: string | number | null
  ppt_options: string | number | (string | number)[] | null
  min_sum_assured: number | null
  max_sum_assured: number | null
}

export interface Premium {
  modes: string[]
  modal_factors: Record<string, number> | null
  high_sa_rebate: string | null
  mode_rebate: string | null
  gst_applicable: boolean
}

export interface Benefits {
  death_benefit: string | null
  maturity_benefit: string | null
  survival_benefit: string | null
  bonus_type: string | null
}

export interface SurrenderLoan {
  surrender: string
  loan: string
}

export interface LICProduct {
  plan_name: string
  plan_no: number | null
  uin: string
  category: string
  nature: Nature
  status: string
  eligibility: Eligibility
  premium: Premium
  benefits: Benefits
  riders_allowed: string[]
  surrender_loan: SurrenderLoan
  last_updated: string
}

export const lic_products: LICProduct[] = [
  {
    plan_name: "LIC's Single Premium Endowment Plan",
    plan_no: 717,
    uin: "512N283V03",
    category: "Endowment",
    nature: { participating: true, linked: false, type: "Savings + Protection" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Single"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Single"],
      modal_factors: { single: 1.0 },
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per policy terms; see brochure",
      maturity_benefit: "Sum Assured + bonuses/guaranteed additions as applicable",
      survival_benefit: null,
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's New Endowment Plan",
    plan_no: 714,
    uin: "512N277V03",
    category: "Endowment",
    nature: { participating: true, linked: false, type: "Savings + Protection" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: "12-35 (typical)",
      ppt_options: "Equal to policy term",
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "Sum Assured on Death + vested bonuses + FAB (if any)",
      maturity_benefit: "Basic Sum Assured + vested bonuses + FAB (if any)",
      survival_benefit: null,
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: {
      surrender: "Available after 2 years (typically)",
      loan: "Available after acquiring surrender value",
    },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's New Jeevan Anand",
    plan_no: 715,
    uin: "512N279V03",
    category: "Endowment",
    nature: { participating: true, linked: false, type: "Savings + Whole-life protection post-maturity" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: "Equal to policy term",
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "During term: SA on Death + bonuses; After maturity: whole-life cover (as per brochure)",
      maturity_benefit: "Basic Sum Assured + vested bonuses + FAB (if any)",
      survival_benefit: null,
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Jeevan Lakshya",
    plan_no: 733,
    uin: "512N297V03",
    category: "Endowment",
    nature: { participating: true, linked: false, type: "Family income benefit focus" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "Annual income benefit + lumpsum at maturity (as per brochure)",
      maturity_benefit: "Basic Sum Assured + bonuses",
      survival_benefit: null,
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
  plan_name: "LIC's Jeevan Tarun",
  plan_no: 734,
  uin: "512N299V03",
  category: "Child",
  nature: { participating: true, linked: false, type: "Savings + Protection" },
  status: "Active",
  eligibility: {
    min_age: 0.08,                // 30 days ≈ 0.08 years
    max_age: 12,
    term_range_years: "13-25",    // policy term = 25 - entry_age; range for entry ages 0–12
    ppt_options: "20 - age at entry (years)",
    min_sum_assured: 200000,
    max_sum_assured: null,
  },
  premium: {
    modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
    modal_factors: null,
    high_sa_rebate: null,
    mode_rebate: null,
    gst_applicable: true,
  },
  benefits: {
    death_benefit: "Higher of 125% of Basic Sum Assured or 7 × annualised premium, subject to minimum 105% of premiums paid",
    maturity_benefit: "Basic Sum Assured + vested bonuses + FAB (if any)",
    survival_benefit: "Optional staged survival payouts at child ages 20-24 (5% / 10% / 15% options)",
    bonus_type: "Reversionary + Final (if declared)",
  },
  riders_allowed: [
    "Premium Waiver Benefit Rider",
    "Accidental Death & Disability Benefit Rider",
  ],
  surrender_loan: {
    surrender: "Surrender as per brochure; loan facility subject to terms after the lock-in",
    loan: "Loan available as per corporation rules and policy terms",
  },
  last_updated: new Date().toISOString(),
},
  {
    plan_name: "LIC's Jeevan Labh",
    plan_no: 736,
    uin: "512N304V03",
    category: "Endowment",
    nature: { participating: true, linked: false, type: "Limited premium payment endowment" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: [10, 15, 16],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "BSA + bonuses",
      survival_benefit: null,
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Amritbaal",
    plan_no: 774,
    uin: "512N365V02",
    category: "Endowment",
    nature: { participating: false, linked: false, type: "Child savings plan with guaranteed additions" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Single", "Limited"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)", "Single"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "Guaranteed additions + sum assured as per terms",
      survival_benefit: null,
      bonus_type: "Guaranteed Additions (Non-Par)",
    },
    riders_allowed: ["Premium Waiver Benefit Rider"],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Bima Jyoti",
    plan_no: 760,
    uin: "512N339V03",
    category: "Endowment",
    nature: { participating: false, linked: false, type: "Guaranteed additions (Non-Par)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "Sum Assured + Guaranteed Additions",
      survival_benefit: null,
      bonus_type: "Guaranteed Additions",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Jeevan Azad",
    plan_no: 768,
    uin: "512N348V02",
    category: "Endowment",
    nature: { participating: true, linked: false, type: "Limited premium, guaranteed maturity SA" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "Guaranteed maturity amount (as per terms) + bonus if applicable",
      survival_benefit: null,
      bonus_type: "Reversionary/Guaranteed per brochure",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC’s Nav Jeevan Shree",
    plan_no: 912,
    uin: "512N387V01",
    category: "Endowment",
    nature: { participating: true, linked: false, type: "High net-worth endowment (as per brochure)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "As per brochure",
      survival_benefit: null,
      bonus_type: "As declared",
    },
    riders_allowed: ["As permitted"],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC’s Nav Jeevan Shree - Single Premium",
    plan_no: 911,
    uin: "512N390V01",
    category: "Endowment",
    nature: { participating: true, linked: false, type: "Single premium endowment (HNI focus)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Single"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Single"],
      modal_factors: { single: 1.0 },
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "As per brochure",
      survival_benefit: null,
      bonus_type: "As declared",
    },
    riders_allowed: ["As permitted"],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Jeevan Umang",
    plan_no: 745,
    uin: "512N312V03",
    category: "Whole Life",
    nature: { participating: true, linked: false, type: "Whole life with guaranteed annual survival benefits" },
    status: "Active",
    eligibility: {
      min_age: 0.25,
      max_age: 55,
      term_range_years: "Up to age 100 maturity; PPT 15/20/25/30",
      ppt_options: [15, 20, 25, 30],
      min_sum_assured: 200000,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "As per brochure at age 100",
      survival_benefit: "8% of Basic Sum Assured annually after PPT till maturity",
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Jeevan Utsav",
    plan_no: 771,
    uin: "512N363V02",
    category: "Whole Life",
    nature: { participating: true, linked: false, type: "Whole life with guaranteed income features (as per brochure)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: null,
      survival_benefit: "As per brochure",
      bonus_type: "As declared",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC’s Bima Shree",
    plan_no: 748,
    uin: "512N316V03",
    category: "Money Back",
    nature: { participating: true, linked: false, type: "Guaranteed money-back for HNI (as per brochure)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "As per brochure",
      survival_benefit: "Money-back at intervals",
      bonus_type: "As declared",
    },
    riders_allowed: ["As permitted"],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's New Money Back Plan-20 Years",
    plan_no: 720,
    uin: "512N280V03",
    category: "Money Back",
    nature: { participating: true, linked: false, type: "Money back every 5 years; maturity at end" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: 20,
      ppt_options: "15 years (typical)",
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "Balance + bonuses",
      survival_benefit: "20% of SA at intervals",
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's New Money Back Plan-25 Years",
    plan_no: 721,
    uin: "512N278V03",
    category: "Money Back",
    nature: { participating: true, linked: false, type: "Money back every 5 years; maturity at end" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: 25,
      ppt_options: "20 years (typical)",
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "Balance + bonuses",
      survival_benefit: "15% of SA at intervals",
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: [
      "Accident Benefit Rider",
      "Accidental Death & Disability Benefit Rider",
      "New Term Assurance Rider",
      "Premium Waiver Benefit Rider",
    ],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's New Children's Money Back Plan",
    plan_no: 732,
    uin: "512N296V03",
    category: "Money Back",
    nature: { participating: true, linked: false, type: "Child education milestones" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "As per brochure",
      survival_benefit: "Periodic money-back as per ages",
      bonus_type: "Reversionary + Final (if declared)",
    },
    riders_allowed: ["Premium Waiver Benefit Rider"],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Bima Ratna",
    plan_no: 764,
    uin: "512N345V02",
    category: "Money Back",
    nature: { participating: true, linked: false, type: "Guaranteed money-back + loyalty additions (as declared)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: "As per brochure",
      survival_benefit: "Money-back at set intervals",
      bonus_type: "As declared",
    },
    riders_allowed: ["As permitted"],
    surrender_loan: { surrender: "As per brochure", loan: "As per brochure" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC’s Digi Term",
    plan_no: 876,
    uin: "512N356V02",
    category: "Term",
    nature: { participating: false, linked: false, type: "Pure term (online/offline)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Regular", "Limited", "Single (if any)"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "Sum assured options as per brochure",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: ["Accident Benefit Rider (if permitted)"],
    surrender_loan: { surrender: "Typically none", loan: "Not applicable" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC’s Digi Credit Life",
    plan_no: 878,
    uin: "512N358V01",
    category: "Term",
    nature: { participating: false, linked: false, type: "Credit life" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Single/Regular"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Single", "Regular"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "Declining level cover for loans (as per brochure)",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: [],
    surrender_loan: { surrender: "As per brochure", loan: "Not applicable" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC’s Yuva Credit Life",
    plan_no: 877,
    uin: "512N357V01",
    category: "Term",
    nature: { participating: false, linked: false, type: "Credit life (youth focus)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Single/Regular"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Single", "Regular"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per brochure",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: [],
    surrender_loan: { surrender: "As per brochure", loan: "Not applicable" },
    last_updated: new Date().toISOString(),
  },
 
  {
    plan_name: "LIC’s Yuva Term",
    plan_no: 875,
    uin: "512N355V02",
    category: "Term",
    nature: { participating: false, linked: false, type: "Pure term (youth focus)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Regular", "Limited", "Single (if any)"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "Sum assured options as per brochure",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: ["Accident Benefit Rider (if permitted)"],
    surrender_loan: { surrender: "Typically none", loan: "Not applicable" },
    last_updated: new Date().toISOString(),
  },
  {
  plan_name: "LIC's Index Plus+",
  plan_no: 873,
  uin: "512L354V01",
  category: "ULIP",
  nature: { participating: false, linked: true, type: "Savings + Protection" },
  status: "Active",
  eligibility: {
    min_age: 0.25,                
    max_age: 50,
    term_range_years: "10-25",
    ppt_options: [10, 15, 20, 25],
    min_sum_assured: null,
    max_sum_assured: null,
  },
  premium: {
    modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
    modal_factors: null,
    high_sa_rebate: null,
    mode_rebate: null,
    gst_applicable: true,
  },
  benefits: {
    death_benefit: "As per policy terms — typically higher of Fund Value or Sum Assured as per the brochure",
    maturity_benefit: "Fund Value subject to policy terms",
    survival_benefit: null,
    bonus_type: null,
  },
  riders_allowed: [
    "Accident Benefit Rider",
    "Accidental Death & Disability Benefit Rider",
    "Premium Waiver Benefit Rider",
  ],
  surrender_loan: {
    surrender: "Allowed after lock-in period of 5 years; surrender value as per policy terms",
    loan: "Loan subject to policy terms and fund value availability",
  },
  last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's New Tech-Term",
    plan_no: 954,
    uin: "512N351V02",
    category: "Term",
    nature: { participating: false, linked: false, type: "Pure term (online)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Regular", "Limited"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "Level/increasing cover options as per brochure",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: ["Accident Benefit Rider (if permitted)"],
    surrender_loan: { surrender: "Typically none", loan: "Not applicable" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's New Jeevan Amar",
    plan_no: 955,
    uin: "512N350V02",
    category: "Term",
    nature: { participating: false, linked: false, type: "Pure term (offline)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Regular", "Limited"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "Level/increasing cover options as per brochure",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: ["Accident Benefit Rider (if permitted)"],
    surrender_loan: { surrender: "Typically none", loan: "Not applicable" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Saral Jeevan Bima",
    plan_no: 859,
    uin: "512N341V01",
    category: "Term",
    nature: { participating: false, linked: false, type: "Standard term (IRDAI)" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: ["Single/Regular"],
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: ["Yearly", "Half-Yearly", "Quarterly", "Monthly (NACH/Salary)", "Single"],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: true,
    },
    benefits: {
      death_benefit: "As per standard product guidelines",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: ["Accident Benefit Rider (if permitted)"],
    surrender_loan: { surrender: "As per product rules", loan: "Not applicable" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Accident Benefit Rider",
    plan_no: null,
    uin: "512B203V03",
    category: "Rider",
    nature: { participating: false, linked: false, type: "Rider" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: [],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: false,
    },
    benefits: {
      death_benefit: "Pays additional amount on accidental death; disability benefits as per rider terms",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: [],
    surrender_loan: { surrender: "", loan: "" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Premium Waiver Benefit Rider",
    plan_no: null,
    uin: "512B204V04",
    category: "Rider",
    nature: { participating: false, linked: false, type: "Rider" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: [],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: false,
    },
    benefits: {
      death_benefit: "Waives future premiums on specified events (typically death/disablement of proposer in child plans)",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: [],
    surrender_loan: { surrender: "", loan: "" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Accidental Death & Disability Benefit Rider",
    plan_no: null,
    uin: "512B209V02",
    category: "Rider",
    nature: { participating: false, linked: false, type: "Rider" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: [],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: false,
    },
    benefits: {
      death_benefit: "Additional sum assured on accidental death; disability income/waiver per rider",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: [],
    surrender_loan: { surrender: "", loan: "" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's New Term Assurance Rider",
    plan_no: null,
    uin: "512B210V02",
    category: "Rider",
    nature: { participating: false, linked: false, type: "Rider" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: [],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: false,
    },
    benefits: {
      death_benefit: "Adds extra life cover (level term) over base plan",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: [],
    surrender_loan: { surrender: "", loan: "" },
    last_updated: new Date().toISOString(),
  },
  {
    plan_name: "LIC's Linked Accidental Death Benefit Rider",
    plan_no: null,
    uin: "512A211V02",
    category: "Rider",
    nature: { participating: false, linked: true, type: "ULIP Rider" },
    status: "Active",
    eligibility: {
      min_age: null,
      max_age: null,
      term_range_years: null,
      ppt_options: null,
      min_sum_assured: null,
      max_sum_assured: null,
    },
    premium: {
      modes: [],
      modal_factors: null,
      high_sa_rebate: null,
      mode_rebate: null,
      gst_applicable: false,
    },
    benefits: {
      death_benefit: "Accidental death benefit rider for ULIP products",
      maturity_benefit: null,
      survival_benefit: null,
      bonus_type: null,
    },
    riders_allowed: [],
    surrender_loan: { surrender: "", loan: "" },
    last_updated: new Date().toISOString(),
  },
]

